### ISSUE TITLE
Unable to make own pbta/motw playbook while this module is in use

### ISSUE THREAD

**Issue by Eilavamp** [Rangertheman/motw-for-pbta#20]
Hello, I'm trying to add the fan-made playbooks to this addon, specifically the Mad Scientist, however when I follow the pbta guide on making a new playbook I am met with the error "sheet configuration has been disabled due to a module that is providing it". Is it this addon that is preventing me from doing this, and if so how can a new playbook be added to this system by a user?

**Comment by Eilavamp** [comment]
![image](https://github.com/user-attachments/assets/7b82f659-116f-41a8-9771-fbbe2fccff2d)

**Comment by Rangertheman** [comment]
Thanks for using the MotW module!

You should be able to create a new Playbook from the Create Item meny.

![image](https://github.com/user-attachments/assets/6df814cf-8291-445c-a42a-13b51073d769)
