### ISSUE TITLE
Archetype weapons unusable

### ISSUE THREAD

**Issue by Pantus** [Rangertheman/motw-for-pbta#4]
Whem I create a chosen and check for "The Chosen: Weapons", I can see that "Business-end: artifact" depends on "@UUID[Item.0LGKzof6dXx8GQyc]{magic}". Same with other weapons, 1-harm is an item and all.

**Comment by Rangertheman** [comment]
Thanks for noticing! I had dragged tags onto the items but hadn't included the tags folder. This should be resolved with version 0.1.1 of the module, which I have just released.
