### ISSUE TITLE
Unable to install module

### ISSUE THREAD

**Issue by pooya-raz** [Rangertheman/motw-for-pbta#6]
Sucessfully installed on Linux, but just tried installing this module on a Mac but got the following error:

<img width="1238" alt="Screenshot 2023-07-01 at 21 00 58" src="https://github.com/Rangertheman/motw-for-pbta/assets/1034999/9ec84caa-ab24-47af-a3cd-5592ebe7de43">

Foundary VTT version: 11 Build 304

**Comment by Rangertheman** [comment]
Thanks for your report! 

I haven't been able to replicate the error on any operating system. A friend has tested it on MacOS and I have tested it on Windows 11.
